### ISSUE TITLE
Sound class fails to load mp3

### ISSUE THREAD

**Issue by EdgarK** [rubygame/rubygame#20]
When I'm using Music class everything is working fine (it loads wave, mp3 etc).

But the goal is to play two or more songs in one time.
The documentation says that to play couple of tracks in one time I should use Sound class. And It should work the same.

When I'm using Sound class instead of Music it fails to load mp3 files but works with wave ones.

```... rubygame/sound.rb:79:in`load': Could not load Sound file 'song.mp3':
 Unrecognized sound file type (Rubygame::SDLError)
    from game.rb:82:in `block in <main>' ...

```
```

**Comment by jacius** [comment]
Rubygame uses SDL_Mixer for music and sounds. For some reason, SDL_Mixer can't load MP3 files for use as sounds, it can only load them for music (which is a totally separate subsystem of SDL_Mixer). So, there's nothing I can do in Rubygame to fix it. I would recommend converting your songs to Ogg Vorbis format as a work-around.

**Comment by EdgarK** [comment]
Thanks for your reply.
Ogg Vorbis wouldn't work for me. I will search some other solutions.
You should remove mp3 from Sound class documentation, I think.
